name: Versioned
on:
  push:
    tags:
      - "v*"

jobs:
  Build:
    name: "Build on ${{ matrix.os }} with ${{ matrix.shell }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        shell: [pwsh]
        include:
          - os: windows-latest
            shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        shell: "${{ matrix.shell }}"
        run: |
          ./Build.ps1 -Stages Build,Test

  Linting:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Super Linter"
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: [Build, Linting]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Publish
        shell: pwsh
        run: |
          ./Build.ps1 -Stages Build,Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
